---
# Delete of the Oracle VM instance
- name: Task to delete the Oracle VM instance
  gcp_compute_instance:
    name: "{{ gcp_instance_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

# Delete of the Static IP Address
- name: Task to delete an address
  gcp_compute_address:
    name: "{{ gcp_instance_name }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

# Delete of the firewall
- name: Task to delete a firewall
  gcp_compute_firewall:
    name: "{{ gcp_firewall_name }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"    
    state: absent

# We register the network, so we can delete the subnetwork
- name: Task to register the existing network so we can delete it
  gcp_compute_network:
    name: "{{ gcp_network_name }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: network

# Delete of the subnetwork
- name: Task to delete a subnetwork
  gcp_compute_subnetwork:
    name: "{{ gcp_subnet_name }}"
    region: "{{ gcp_region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ gcp_ip_cidr_range }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

# Delete of the network
- name: Task to delete a network
  gcp_compute_network:
    name: "{{ gcp_network_name }}"
    project: "{{ gcp_cred_file }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
